#!/usr/bin/env python3
"""Build preview/tokens.css from the Tufte theme, read-only on the vault.

The preview exists so the sheet can be looked at in a browser in the type and
the colours Obsidian will actually give it.  That means copying two things out
of the theme: the two et-book @font-face blocks (roman and italic — bold is
never set on this sheet) and the light/dark custom properties.

The theme is not ours to trust blindly even though it is: a @font-face block
is copied only when it contains no `<`, no backslash, and no url() that is not
a data: URI, so nothing this writes can smuggle markup, a CSS escape, or a
network fetch into the preview page.

Usage:  PYTHONDONTWRITEBYTECODE=1 python3 preview/build_preview.py
"""

import os
import re
import sys

VAULT = os.environ.get(
    "TUFTE_VAULT",
    os.path.expanduser(
        "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/TufteCSSDev"))
THEME = os.path.join(VAULT, ".obsidian", "themes", "Tufte", "theme.css")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tokens.css")

FACE_RE = re.compile(r"@font-face\s*\{[^{}]*\}", re.DOTALL)
URL_RE = re.compile(r"url\(\s*[\"']?([^\"')]*)", re.IGNORECASE)

# The Tufte palettes, from tufte_style.py — the literal custom properties of
# the theme, restated here because the preview has no Obsidian to inherit them
# from and must not depend on parsing the theme's cascade.
LIGHT = {
    "--tufte-bg": "#fffff8",
    "--tufte-bg-alt": "#f7f7ef",
    "--tufte-ink": "#111111",
    "--tufte-muted": "#555555",
    "--tufte-faint": "#6f6f6f",
    "--tufte-rule": "#cccccc",
    "--tufte-accent": "#a00000",
}
DARK = {
    "--tufte-bg": "#151515",
    "--tufte-bg-alt": "#1c1c1c",
    "--tufte-ink": "#e8e6d9",
    "--tufte-muted": "#a59f8c",
    "--tufte-faint": "#908b7a",
    "--tufte-rule": "#3a3a36",
    "--tufte-accent": "#d97474",
}


def safe(block: str) -> bool:
    if "<" in block or "\\" in block:
        return False
    for href in URL_RE.findall(block):
        if not href.startswith("data:"):
            return False
    return True


def wanted(block: str) -> bool:
    if 'font-family: "et-book"' not in block:
        return False
    if "font-weight: bold" in block:
        return False
    return True


def main() -> int:
    if not os.path.exists(THEME):
        print(f"theme.css not found at {THEME}", file=sys.stderr)
        return 1
    with open(THEME, encoding="utf-8") as fh:
        css = fh.read()

    faces = []
    for block in FACE_RE.findall(css):
        if not wanted(block):
            continue
        if not safe(block):
            print("  refused an unsafe @font-face block", file=sys.stderr)
            continue
        faces.append(block)
    if len(faces) != 2:
        print(f"  warning: expected 2 et-book faces, copied {len(faces)}",
              file=sys.stderr)

    def block(selector, tokens):
        rows = "\n".join(f"  {k}: {v};" for k, v in tokens.items())
        return f"{selector} {{\n{rows}\n}}\n"

    out = [
        "/* GENERATED by preview/build_preview.py — do not hand-edit.",
        "   The et-book faces are copied verbatim from the Tufte theme;",
        "   the tokens are the theme's own light and dark palettes. */",
        "",
        "\n".join(faces),
        "",
        block(":root, :root[data-theme=\"light\"]", LIGHT),
        block(":root[data-theme=\"dark\"]", DARK),
    ]
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"  tokens.css -> {OUT}  ({os.path.getsize(OUT)} bytes, "
          f"{len(faces)} faces)")
    return 0


if __name__ == "__main__":
    sys.dont_write_bytecode = True
    raise SystemExit(main())
